
export const iconTypes = [
    "fa-glass",
    "fa-music",
    "fa-search",
    "fa-envelope-o",
    "fa-heart",
    "fa-star",
    "fa-star-o",
    "fa-user",
    "fa-film",
    "fa-th-large",
    "fa-th",
    "fa-th-list",
    "fa-check",
    "fa-remove",
    "fa-close",
    "fa-times",
    "fa-search-plus",
    "fa-search-minus",
    "fa-power-off",
    "fa-signal",
    "fa-gear",
    "fa-cog",
    "fa-trash-o",
    "fa-home",
    "fa-file-o",
    "fa-clock-o",
    "fa-road",
    "fa-download",
    "fa-arrow-circle-o-down",
    "fa-arrow-circle-o-up",
    "fa-inbox",
    "fa-play-circle-o",
    "fa-rotate-right",
    "fa-repeat",
    "fa-refresh",
    "fa-list-alt",
    "fa-lock",
    "fa-flag",
    "fa-headphones",
    "fa-volume-off",
    "fa-volume-down",
    "fa-volume-up",
    "fa-qrcode",
    "fa-barcode",
    "fa-tag",
    "fa-tags",
    "fa-book",
    "fa-bookmark",
    "fa-print",
    "fa-camera",
    "fa-font",
    "fa-bold",
    "fa-italic",
    "fa-text-height",
    "fa-text-width",
    "fa-align-left",
    "fa-align-center",
    "fa-align-right",
    "fa-align-justify",
    "fa-list",
    "fa-dedent",
    "fa-outdent",
    "fa-indent",
    "fa-video-camera",
    "fa-photo",
    "fa-image",
    "fa-picture-o",
    "fa-pencil",
    "fa-map-marker",
    "fa-adjust",
    "fa-tint",
    "fa-edit",
    "fa-pencil-square-o",
    "fa-share-square-o",
    "fa-check-square-o",
    "fa-arrows",
    "fa-step-backward",
    "fa-fast-backward",
    "fa-backward",
    "fa-play",
    "fa-pause",
    "fa-stop",
    "fa-forward",
    "fa-fast-forward",
    "fa-step-forward",
    "fa-eject",
    "fa-chevron-left",
    "fa-chevron-right",
    "fa-plus-circle",
    "fa-minus-circle",
    "fa-times-circle",
    "fa-check-circle",
    "fa-question-circle",
    "fa-info-circle",
    "fa-crosshairs",
    "fa-times-circle-o",
    "fa-check-circle-o",
    "fa-ban",
    "fa-arrow-left",
    "fa-arrow-right",
    "fa-arrow-up",
    "fa-arrow-down",
    "fa-mail-forward",
    "fa-share",
    "fa-expand",
    "fa-compress",
    "fa-plus",
    "fa-minus",
    "fa-asterisk",
    "fa-exclamation-circle",
    "fa-gift",
    "fa-leaf",
    "fa-fire",
    "fa-eye",
    "fa-eye-slash",
    "fa-warning",
    "fa-exclamation-triangle",
    "fa-plane",
    "fa-calendar",
    "fa-random",
    "fa-comment",
    "fa-magnet",
    "fa-chevron-up",
    "fa-chevron-down",
    "fa-retweet",
    "fa-shopping-cart",
    "fa-folder",
    "fa-folder-open",
    "fa-arrows-v",
    "fa-arrows-h",
    "fa-bar-chart-o",
    "fa-bar-chart",
    "fa-twitter-square",
    "fa-facebook-square",
    "fa-camera-retro",
    "fa-key",
    "fa-gears",
    "fa-cogs",
    "fa-comments",
    "fa-thumbs-o-up",
    "fa-thumbs-o-down",
    "fa-star-half",
    "fa-heart-o",
    "fa-sign-out",
    "fa-linkedin-square",
    "fa-thumb-tack",
    "fa-external-link",
    "fa-sign-in",
    "fa-trophy",
    "fa-github-square",
    "fa-upload",
    "fa-lemon-o",
    "fa-phone",
    "fa-square-o",
    "fa-bookmark-o",
    "fa-phone-square",
    "fa-twitter",
    "fa-facebook-f",
    "fa-facebook",
    "fa-github",
    "fa-unlock",
    "fa-credit-card",
    "fa-feed",
    "fa-rss",
    "fa-hdd-o",
    "fa-bullhorn",
    "fa-bell",
    "fa-certificate",
    "fa-hand-o-right",
    "fa-hand-o-left",
    "fa-hand-o-up",
    "fa-hand-o-down",
    "fa-arrow-circle-left",
    "fa-arrow-circle-right",
    "fa-arrow-circle-up",
    "fa-arrow-circle-down",
    "fa-globe",
    "fa-wrench",
    "fa-tasks",
    "fa-filter",
    "fa-briefcase",
    "fa-arrows-alt",
    "fa-group",
    "fa-users",
    "fa-chain",
    "fa-link",
    "fa-cloud",
    "fa-flask",
    "fa-cut",
    "fa-scissors",
    "fa-copy",
    "fa-files-o",
    "fa-paperclip",
    "fa-save",
    "fa-floppy-o",
    "fa-square",
    "fa-navicon",
    "fa-reorder",
    "fa-bars",
    "fa-list-ul",
    "fa-list-ol",
    "fa-strikethrough",
    "fa-underline",
    "fa-table",
    "fa-magic",
    "fa-truck",
    "fa-pinterest",
    "fa-pinterest-square",
    "fa-google-plus-square",
    "fa-google-plus",
    "fa-money",
    "fa-caret-down",
    "fa-caret-up",
    "fa-caret-left",
    "fa-caret-right",
    "fa-columns",
    "fa-unsorted",
    "fa-sort",
    "fa-sort-down",
    "fa-sort-desc",
    "fa-sort-up",
    "fa-sort-asc",
    "fa-envelope",
    "fa-linkedin",
    "fa-rotate-left",
    "fa-undo",
    "fa-legal",
    "fa-gavel",
    "fa-dashboard",
    "fa-tachometer",
    "fa-comment-o",
    "fa-comments-o",
    "fa-flash",
    "fa-bolt",
    "fa-sitemap",
    "fa-umbrella",
    "fa-paste",
    "fa-clipboard",
    "fa-lightbulb-o",
    "fa-exchange",
    "fa-cloud-download",
    "fa-cloud-upload",
    "fa-user-md",
    "fa-stethoscope",
    "fa-suitcase",
    "fa-bell-o",
    "fa-coffee",
    "fa-cutlery",
    "fa-file-text-o",
    "fa-building-o",
    "fa-hospital-o",
    "fa-ambulance",
    "fa-medkit",
    "fa-fighter-jet",
    "fa-beer",
    "fa-h-square",
    "fa-plus-square",
    "fa-angle-double-left",
    "fa-angle-double-right",
    "fa-angle-double-up",
    "fa-angle-double-down",
    "fa-angle-left",
    "fa-angle-right",
    "fa-angle-up",
    "fa-angle-down",
    "fa-desktop",
    "fa-laptop",
    "fa-tablet",
    "fa-mobile-phone",
    "fa-mobile",
    "fa-circle-o",
    "fa-quote-left",
    "fa-quote-right",
    "fa-spinner",
    "fa-circle",
    "fa-mail-reply",
    "fa-reply",
    "fa-github-alt",
    "fa-folder-o",
    "fa-folder-open-o",
    "fa-smile-o",
    "fa-frown-o",
    "fa-meh-o",
    "fa-gamepad",
    "fa-keyboard-o",
    "fa-flag-o",
    "fa-flag-checkered",
    "fa-terminal",
    "fa-code",
    "fa-mail-reply-all",
    "fa-reply-all",
    "fa-star-half-empty",
    "fa-star-half-full",
    "fa-star-half-o",
    "fa-location-arrow",
    "fa-crop",
    "fa-code-fork",
    "fa-unlink",
    "fa-chain-broken",
    "fa-question",
    "fa-info",
    "fa-exclamation",
    "fa-superscript",
    "fa-subscript",
    "fa-eraser",
    "fa-puzzle-piece",
    "fa-microphone",
    "fa-microphone-slash",
    "fa-shield",
    "fa-calendar-o",
    "fa-fire-extinguisher",
    "fa-rocket",
    "fa-maxcdn",
    "fa-chevron-circle-left",
    "fa-chevron-circle-right",
    "fa-chevron-circle-up",
    "fa-chevron-circle-down",
    "fa-html5",
    "fa-css3",
    "fa-anchor",
    "fa-unlock-alt",
    "fa-bullseye",
    "fa-ellipsis-h",
    "fa-ellipsis-v",
    "fa-rss-square",
    "fa-play-circle",
    "fa-ticket",
    "fa-minus-square",
    "fa-minus-square-o",
    "fa-level-up",
    "fa-level-down",
    "fa-check-square",
    "fa-pencil-square",
    "fa-external-link-square",
    "fa-share-square",
    "fa-compass",
    "fa-toggle-down",
    "fa-caret-square-o-down",
    "fa-toggle-up",
    "fa-caret-square-o-up",
    "fa-toggle-right",
    "fa-caret-square-o-right",
    "fa-euro",
    "fa-eur",
    "fa-gbp",
    "fa-dollar",
    "fa-usd",
    "fa-rupee",
    "fa-inr",
    "fa-cny",
    "fa-rmb",
    "fa-yen",
    "fa-jpy",
    "fa-ruble",
    "fa-rouble",
    "fa-rub",
    "fa-won",
    "fa-krw",
    "fa-bitcoin",
    "fa-btc",
    "fa-file",
    "fa-file-text",
    "fa-sort-alpha-asc",
    "fa-sort-alpha-desc",
    "fa-sort-amount-asc",
    "fa-sort-amount-desc",
    "fa-sort-numeric-asc",
    "fa-sort-numeric-desc",
    "fa-thumbs-up",
    "fa-thumbs-down",
    "fa-youtube-square",
    "fa-youtube",
    "fa-xing",
    "fa-xing-square",
    "fa-youtube-play",
    "fa-dropbox",
    "fa-stack-overflow",
    "fa-instagram",
    "fa-flickr",
    "fa-adn",
    "fa-bitbucket",
    "fa-bitbucket-square",
    "fa-tumblr",
    "fa-tumblr-square",
    "fa-long-arrow-down",
    "fa-long-arrow-up",
    "fa-long-arrow-left",
    "fa-long-arrow-right",
    "fa-apple",
    "fa-windows",
    "fa-android",
    "fa-linux",
    "fa-dribbble",
    "fa-skype",
    "fa-foursquare",
    "fa-trello",
    "fa-female",
    "fa-male",
    "fa-gittip",
    "fa-gratipay",
    "fa-sun-o",
    "fa-moon-o",
    "fa-archive",
    "fa-bug",
    "fa-vk",
    "fa-weibo",
    "fa-renren",
    "fa-pagelines",
    "fa-stack-exchange",
    "fa-arrow-circle-o-right",
    "fa-arrow-circle-o-left",
    "fa-toggle-left",
    "fa-caret-square-o-left",
    "fa-dot-circle-o",
    "fa-wheelchair",
    "fa-vimeo-square",
    "fa-turkish-lira",
    "fa-try",
    "fa-plus-square-o",
    "fa-space-shuttle",
    "fa-slack",
    "fa-envelope-square",
    "fa-wordpress",
    "fa-openid",
    "fa-institution",
    "fa-bank",
    "fa-university",
    "fa-mortar-board",
    "fa-graduation-cap",
    "fa-yahoo",
    "fa-google",
    "fa-reddit",
    "fa-reddit-square",
    "fa-stumbleupon-circle",
    "fa-stumbleupon",
    "fa-delicious",
    "fa-digg",
    "fa-pied-piper-pp",
    "fa-pied-piper-alt",
    "fa-drupal",
    "fa-joomla",
    "fa-language",
    "fa-fax",
    "fa-building",
    "fa-child",
    "fa-paw",
    "fa-spoon",
    "fa-cube",
    "fa-cubes",
    "fa-behance",
    "fa-behance-square",
    "fa-steam",
    "fa-steam-square",
    "fa-recycle",
    "fa-automobile",
    "fa-car",
    "fa-cab",
    "fa-taxi",
    "fa-tree",
    "fa-spotify",
    "fa-deviantart",
    "fa-soundcloud",
    "fa-database",
    "fa-file-pdf-o",
    "fa-file-word-o",
    "fa-file-excel-o",
    "fa-file-powerpoint-o",
    "fa-file-photo-o",
    "fa-file-picture-o",
    "fa-file-image-o",
    "fa-file-zip-o",
    "fa-file-archive-o",
    "fa-file-sound-o",
    "fa-file-audio-o",
    "fa-file-movie-o",
    "fa-file-video-o",
    "fa-file-code-o",
    "fa-vine",
    "fa-codepen",
    "fa-jsfiddle",
    "fa-life-bouy",
    "fa-life-buoy",
    "fa-life-saver",
    "fa-support",
    "fa-life-ring",
    "fa-circle-o-notch",
    "fa-ra",
    "fa-resistance",
    "fa-rebel",
    "fa-ge",
    "fa-empire",
    "fa-git-square",
    "fa-git",
    "fa-y-combinator-square",
    "fa-yc-square",
    "fa-hacker-news",
    "fa-tencent-weibo",
    "fa-qq",
    "fa-wechat",
    "fa-weixin",
    "fa-send",
    "fa-paper-plane",
    "fa-send-o",
    "fa-paper-plane-o",
    "fa-history",
    "fa-circle-thin",
    "fa-header",
    "fa-paragraph",
    "fa-sliders",
    "fa-share-alt",
    "fa-share-alt-square",
    "fa-bomb",
    "fa-soccer-ball-o",
    "fa-futbol-o",
    "fa-tty",
    "fa-binoculars",
    "fa-plug",
    "fa-slideshare",
    "fa-twitch",
    "fa-yelp",
    "fa-newspaper-o",
    "fa-wifi",
    "fa-calculator",
    "fa-paypal",
    "fa-google-wallet",
    "fa-cc-visa",
    "fa-cc-mastercard",
    "fa-cc-discover",
    "fa-cc-amex",
    "fa-cc-paypal",
    "fa-cc-stripe",
    "fa-bell-slash",
    "fa-bell-slash-o",
    "fa-trash",
    "fa-copyright",
    "fa-at",
    "fa-eyedropper",
    "fa-paint-brush",
    "fa-birthday-cake",
    "fa-area-chart",
    "fa-pie-chart",
    "fa-line-chart",
    "fa-lastfm",
    "fa-lastfm-square",
    "fa-toggle-off",
    "fa-toggle-on",
    "fa-bicycle",
    "fa-bus",
    "fa-ioxhost",
    "fa-angellist",
    "fa-cc",
    "fa-shekel",
    "fa-sheqel",
    "fa-ils",
    "fa-meanpath",
    "fa-buysellads",
    "fa-connectdevelop",
    "fa-dashcube",
    "fa-forumbee",
    "fa-leanpub",
    "fa-sellsy",
    "fa-shirtsinbulk",
    "fa-simplybuilt",
    "fa-skyatlas",
    "fa-cart-plus",
    "fa-cart-arrow-down",
    "fa-diamond",
    "fa-ship",
    "fa-user-secret",
    "fa-motorcycle",
    "fa-street-view",
    "fa-heartbeat",
    "fa-venus",
    "fa-mars",
    "fa-mercury",
    "fa-intersex",
    "fa-transgender",
    "fa-transgender-alt",
    "fa-venus-double",
    "fa-mars-double",
    "fa-venus-mars",
    "fa-mars-stroke",
    "fa-mars-stroke-v",
    "fa-mars-stroke-h",
    "fa-neuter",
    "fa-genderless",
    "fa-facebook-official",
    "fa-pinterest-p",
    "fa-whatsapp",
    "fa-server",
    "fa-user-plus",
    "fa-user-times",
    "fa-hotel",
    "fa-bed",
    "fa-viacoin",
    "fa-train",
    "fa-subway",
    "fa-medium",
    "fa-yc",
    "fa-y-combinator",
    "fa-optin-monster",
    "fa-opencart",
    "fa-expeditedssl",
    "fa-battery-4",
    "fa-battery",
    "fa-battery-full",
    "fa-battery-3",
    "fa-battery-three-quarters",
    "fa-battery-2",
    "fa-battery-half",
    "fa-battery-1",
    "fa-battery-quarter",
    "fa-battery-0",
    "fa-battery-empty",
    "fa-mouse-pointer",
    "fa-i-cursor",
    "fa-object-group",
    "fa-object-ungroup",
    "fa-sticky-note",
    "fa-sticky-note-o",
    "fa-cc-jcb",
    "fa-cc-diners-club",
    "fa-clone",
    "fa-balance-scale",
    "fa-hourglass-o",
    "fa-hourglass-1",
    "fa-hourglass-start",
    "fa-hourglass-2",
    "fa-hourglass-half",
    "fa-hourglass-3",
    "fa-hourglass-end",
    "fa-hourglass",
    "fa-hand-grab-o",
    "fa-hand-rock-o",
    "fa-hand-stop-o",
    "fa-hand-paper-o",
    "fa-hand-scissors-o",
    "fa-hand-lizard-o",
    "fa-hand-spock-o",
    "fa-hand-pointer-o",
    "fa-hand-peace-o",
    "fa-trademark",
    "fa-registered",
    "fa-creative-commons",
    "fa-gg",
    "fa-gg-circle",
    "fa-tripadvisor",
    "fa-odnoklassniki",
    "fa-odnoklassniki-square",
    "fa-get-pocket",
    "fa-wikipedia-w",
    "fa-safari",
    "fa-chrome",
    "fa-firefox",
    "fa-opera",
    "fa-internet-explorer",
    "fa-tv",
    "fa-television",
    "fa-contao",
    "fa-500px",
    "fa-amazon",
    "fa-calendar-plus-o",
    "fa-calendar-minus-o",
    "fa-calendar-times-o",
    "fa-calendar-check-o",
    "fa-industry",
    "fa-map-pin",
    "fa-map-signs",
    "fa-map-o",
    "fa-map",
    "fa-commenting",
    "fa-commenting-o",
    "fa-houzz",
    "fa-vimeo",
    "fa-black-tie",
    "fa-fonticons",
    "fa-reddit-alien",
    "fa-edge",
    "fa-credit-card-alt",
    "fa-codiepie",
    "fa-modx",
    "fa-fort-awesome",
    "fa-usb",
    "fa-product-hunt",
    "fa-mixcloud",
    "fa-scribd",
    "fa-pause-circle",
    "fa-pause-circle-o",
    "fa-stop-circle",
    "fa-stop-circle-o",
    "fa-shopping-bag",
    "fa-shopping-basket",
    "fa-hashtag",
    "fa-bluetooth",
    "fa-bluetooth-b",
    "fa-percent",
    "fa-gitlab",
    "fa-wpbeginner",
    "fa-wpforms",
    "fa-envira",
    "fa-universal-access",
    "fa-wheelchair-alt",
    "fa-question-circle-o",
    "fa-blind",
    "fa-audio-description",
    "fa-volume-control-phone",
    "fa-braille",
    "fa-assistive-listening-systems",
    "fa-asl-interpreting",
    "fa-american-sign-language-interpreting",
    "fa-deafness",
    "fa-hard-of-hearing",
    "fa-deaf",
    "fa-glide",
    "fa-glide-g",
    "fa-signing",
    "fa-sign-language",
    "fa-low-vision",
    "fa-viadeo",
    "fa-viadeo-square",
    "fa-snapchat",
    "fa-snapchat-ghost",
    "fa-snapchat-square",
    "fa-pied-piper",
    "fa-first-order",
    "fa-yoast",
    "fa-themeisle",
    "fa-google-plus-circle",
    "fa-google-plus-official",
    "fa-fa",
    "fa-font-awesome",
    "fa-handshake-o",
    "fa-envelope-open",
    "fa-envelope-open-o",
    "fa-linode",
    "fa-address-book",
    "fa-address-book-o",
    "fa-vcard",
    "fa-address-card",
    "fa-vcard-o",
    "fa-address-card-o",
    "fa-user-circle",
    "fa-user-circle-o",
    "fa-user-o",
    "fa-id-badge",
    "fa-drivers-license",
    "fa-id-card",
    "fa-drivers-license-o",
    "fa-id-card-o",
    "fa-quora",
    "fa-free-code-camp",
    "fa-telegram",
    "fa-thermometer-4",
    "fa-thermometer",
    "fa-thermometer-full",
    "fa-thermometer-3",
    "fa-thermometer-three-quarters",
    "fa-thermometer-2",
    "fa-thermometer-half",
    "fa-thermometer-1",
    "fa-thermometer-quarter",
    "fa-thermometer-0",
    "fa-thermometer-empty",
    "fa-shower",
    "fa-bathtub",
    "fa-s15",
    "fa-bath",
    "fa-podcast",
    "fa-window-maximize",
    "fa-window-minimize",
    "fa-window-restore",
    "fa-times-rectangle",
    "fa-window-close",
    "fa-times-rectangle-o",
    "fa-window-close-o",
    "fa-bandcamp",
    "fa-grav",
    "fa-etsy",
    "fa-imdb",
    "fa-ravelry",
    "fa-eercast",
    "fa-microchip",
    "fa-snowflake-o",
    "fa-superpowers",
    "fa-wpexplorer",
    "fa-meetup"
];

export enum EnumIconTypes {
    faGlass = "fa-glass",
    faMusic = "fa-music",
    faSearch = "fa-search",
    faEnvelopeO = "fa-envelope-o",
    faHeart = "fa-heart",
    faStar = "fa-star",
    faStarO = "fa-star-o",
    faUser = "fa-user",
    faFilm = "fa-film",
    faThLarge = "fa-th-large",
    faTh = "fa-th",
    faThList = "fa-th-list",
    faCheck = "fa-check",
    faRemove = "fa-remove",
    faClose = "fa-close",
    faTimes = "fa-times",
    faSearchPlus = "fa-search-plus",
    faSearchMinus = "fa-search-minus",
    faPowerOff = "fa-power-off",
    faSignal = "fa-signal",
    faGear = "fa-gear",
    faCog = "fa-cog",
    faTrashO = "fa-trash-o",
    faHome = "fa-home",
    faFileO = "fa-file-o",
    faClockO = "fa-clock-o",
    faRoad = "fa-road",
    faDownload = "fa-download",
    faArrowCircleODown = "fa-arrow-circle-o-down",
    faArrowCircleOUp = "fa-arrow-circle-o-up",
    faInbox = "fa-inbox",
    faPlayCircleO = "fa-play-circle-o",
    faRotateRight = "fa-rotate-right",
    faRepeat = "fa-repeat",
    faRefresh = "fa-refresh",
    faListAlt = "fa-list-alt",
    faLock = "fa-lock",
    faFlag = "fa-flag",
    faHeadphones = "fa-headphones",
    faVolumeOff = "fa-volume-off",
    faVolumeDown = "fa-volume-down",
    faVolumeUp = "fa-volume-up",
    faQrcode = "fa-qrcode",
    faBarcode = "fa-barcode",
    faTag = "fa-tag",
    faTags = "fa-tags",
    faBook = "fa-book",
    faBookmark = "fa-bookmark",
    faPrint = "fa-print",
    faCamera = "fa-camera",
    faFont = "fa-font",
    faBold = "fa-bold",
    faItalic = "fa-italic",
    faTextHeight = "fa-text-height",
    faTextWidth = "fa-text-width",
    faAlignLeft = "fa-align-left",
    faAlignCenter = "fa-align-center",
    faAlignRight = "fa-align-right",
    faAlignJustify = "fa-align-justify",
    faList = "fa-list",
    faDedent = "fa-dedent",
    faOutdent = "fa-outdent",
    faIndent = "fa-indent",
    faVideoCamera = "fa-video-camera",
    faPhoto = "fa-photo",
    faImage = "fa-image",
    faPictureO = "fa-picture-o",
    faPencil = "fa-pencil",
    faMapMarker = "fa-map-marker",
    faAdjust = "fa-adjust",
    faTint = "fa-tint",
    faEdit = "fa-edit",
    faPencilSquareO = "fa-pencil-square-o",
    faShareSquareO = "fa-share-square-o",
    faCheckSquareO = "fa-check-square-o",
    faArrows = "fa-arrows",
    faStepBackward = "fa-step-backward",
    faFastBackward = "fa-fast-backward",
    faBackward = "fa-backward",
    faPlay = "fa-play",
    faPause = "fa-pause",
    faStop = "fa-stop",
    faForward = "fa-forward",
    faFastForward = "fa-fast-forward",
    faStepForward = "fa-step-forward",
    faEject = "fa-eject",
    faChevronLeft = "fa-chevron-left",
    faChevronRight = "fa-chevron-right",
    faPlusCircle = "fa-plus-circle",
    faMinusCircle = "fa-minus-circle",
    faTimesCircle = "fa-times-circle",
    faCheckCircle = "fa-check-circle",
    faQuestionCircle = "fa-question-circle",
    faInfoCircle = "fa-info-circle",
    faCrosshairs = "fa-crosshairs",
    faTimesCircleO = "fa-times-circle-o",
    faCheckCircleO = "fa-check-circle-o",
    faBan = "fa-ban",
    faArrowLeft = "fa-arrow-left",
    faArrowRight = "fa-arrow-right",
    faArrowUp = "fa-arrow-up",
    faArrowDown = "fa-arrow-down",
    faMailForward = "fa-mail-forward",
    faShare = "fa-share",
    faExpand = "fa-expand",
    faCompress = "fa-compress",
    faPlus = "fa-plus",
    faMinus = "fa-minus",
    faAsterisk = "fa-asterisk",
    faExclamationCircle = "fa-exclamation-circle",
    faGift = "fa-gift",
    faLeaf = "fa-leaf",
    faFire = "fa-fire",
    faEye = "fa-eye",
    faEyeSlash = "fa-eye-slash",
    faWarning = "fa-warning",
    faExclamationTriangle = "fa-exclamation-triangle",
    faPlane = "fa-plane",
    faCalendar = "fa-calendar",
    faRandom = "fa-random",
    faComment = "fa-comment",
    faMagnet = "fa-magnet",
    faChevronUp = "fa-chevron-up",
    faChevronDown = "fa-chevron-down",
    faRetweet = "fa-retweet",
    faShoppingCart = "fa-shopping-cart",
    faFolder = "fa-folder",
    faFolderOpen = "fa-folder-open",
    faArrowsV = "fa-arrows-v",
    faArrowsH = "fa-arrows-h",
    faBarChartO = "fa-bar-chart-o",
    faBarChart = "fa-bar-chart",
    faTwitterSquare = "fa-twitter-square",
    faFacebookSquare = "fa-facebook-square",
    faCameraRetro = "fa-camera-retro",
    faKey = "fa-key",
    faGears = "fa-gears",
    faCogs = "fa-cogs",
    faComments = "fa-comments",
    faThumbsOUp = "fa-thumbs-o-up",
    faThumbsODown = "fa-thumbs-o-down",
    faStarHalf = "fa-star-half",
    faHeartO = "fa-heart-o",
    faSignOut = "fa-sign-out",
    faLinkedinSquare = "fa-linkedin-square",
    faThumbTack = "fa-thumb-tack",
    faExternalLink = "fa-external-link",
    faSignIn = "fa-sign-in",
    faTrophy = "fa-trophy",
    faGithubSquare = "fa-github-square",
    faUpload = "fa-upload",
    faLemonO = "fa-lemon-o",
    faPhone = "fa-phone",
    faSquareO = "fa-square-o",
    faBookmarkO = "fa-bookmark-o",
    faPhoneSquare = "fa-phone-square",
    faTwitter = "fa-twitter",
    faFacebookF = "fa-facebook-f",
    faFacebook = "fa-facebook",
    faGithub = "fa-github",
    faUnlock = "fa-unlock",
    faCreditCard = "fa-credit-card",
    faFeed = "fa-feed",
    faRss = "fa-rss",
    faHddO = "fa-hdd-o",
    faBullhorn = "fa-bullhorn",
    faBell = "fa-bell",
    faCertificate = "fa-certificate",
    faHandORight = "fa-hand-o-right",
    faHandOLeft = "fa-hand-o-left",
    faHandOUp = "fa-hand-o-up",
    faHandODown = "fa-hand-o-down",
    faArrowCircleLeft = "fa-arrow-circle-left",
    faArrowCircleRight = "fa-arrow-circle-right",
    faArrowCircleUp = "fa-arrow-circle-up",
    faArrowCircleDown = "fa-arrow-circle-down",
    faGlobe = "fa-globe",
    faWrench = "fa-wrench",
    faTasks = "fa-tasks",
    faFilter = "fa-filter",
    faBriefcase = "fa-briefcase",
    faArrowsAlt = "fa-arrows-alt",
    faGroup = "fa-group",
    faUsers = "fa-users",
    faChain = "fa-chain",
    faLink = "fa-link",
    faCloud = "fa-cloud",
    faFlask = "fa-flask",
    faCut = "fa-cut",
    faScissors = "fa-scissors",
    faCopy = "fa-copy",
    faFilesO = "fa-files-o",
    faPaperclip = "fa-paperclip",
    faSave = "fa-save",
    faFloppyO = "fa-floppy-o",
    faSquare = "fa-square",
    faNavicon = "fa-navicon",
    faReorder = "fa-reorder",
    faBars = "fa-bars",
    faListUl = "fa-list-ul",
    faListOl = "fa-list-ol",
    faStrikethrough = "fa-strikethrough",
    faUnderline = "fa-underline",
    faTable = "fa-table",
    faMagic = "fa-magic",
    faTruck = "fa-truck",
    faPinterest = "fa-pinterest",
    faPinterestSquare = "fa-pinterest-square",
    faGooglePlusSquare = "fa-google-plus-square",
    faGooglePlus = "fa-google-plus",
    faMoney = "fa-money",
    faCaretDown = "fa-caret-down",
    faCaretUp = "fa-caret-up",
    faCaretLeft = "fa-caret-left",
    faCaretRight = "fa-caret-right",
    faColumns = "fa-columns",
    faUnsorted = "fa-unsorted",
    faSort = "fa-sort",
    faSortDown = "fa-sort-down",
    faSortDesc = "fa-sort-desc",
    faSortUp = "fa-sort-up",
    faSortAsc = "fa-sort-asc",
    faEnvelope = "fa-envelope",
    faLinkedin = "fa-linkedin",
    faRotateLeft = "fa-rotate-left",
    faUndo = "fa-undo",
    faLegal = "fa-legal",
    faGavel = "fa-gavel",
    faDashboard = "fa-dashboard",
    faTachometer = "fa-tachometer",
    faCommentO = "fa-comment-o",
    faCommentsO = "fa-comments-o",
    faFlash = "fa-flash",
    faBolt = "fa-bolt",
    faSitemap = "fa-sitemap",
    faUmbrella = "fa-umbrella",
    faPaste = "fa-paste",
    faClipboard = "fa-clipboard",
    faLightbulbO = "fa-lightbulb-o",
    faExchange = "fa-exchange",
    faCloudDownload = "fa-cloud-download",
    faCloudUpload = "fa-cloud-upload",
    faUserMd = "fa-user-md",
    faStethoscope = "fa-stethoscope",
    faSuitcase = "fa-suitcase",
    faBellO = "fa-bell-o",
    faCoffee = "fa-coffee",
    faCutlery = "fa-cutlery",
    faFileTextO = "fa-file-text-o",
    faBuildingO = "fa-building-o",
    faHospitalO = "fa-hospital-o",
    faAmbulance = "fa-ambulance",
    faMedkit = "fa-medkit",
    faFighterJet = "fa-fighter-jet",
    faBeer = "fa-beer",
    faHSquare = "fa-h-square",
    faPlusSquare = "fa-plus-square",
    faAngleDoubleLeft = "fa-angle-double-left",
    faAngleDoubleRight = "fa-angle-double-right",
    faAngleDoubleUp = "fa-angle-double-up",
    faAngleDoubleDown = "fa-angle-double-down",
    faAngleLeft = "fa-angle-left",
    faAngleRight = "fa-angle-right",
    faAngleUp = "fa-angle-up",
    faAngleDown = "fa-angle-down",
    faDesktop = "fa-desktop",
    faLaptop = "fa-laptop",
    faTablet = "fa-tablet",
    faMobilePhone = "fa-mobile-phone",
    faMobile = "fa-mobile",
    faCircleO = "fa-circle-o",
    faQuoteLeft = "fa-quote-left",
    faQuoteRight = "fa-quote-right",
    faSpinner = "fa-spinner",
    faCircle = "fa-circle",
    faMailReply = "fa-mail-reply",
    faReply = "fa-reply",
    faGithubAlt = "fa-github-alt",
    faFolderO = "fa-folder-o",
    faFolderOpenO = "fa-folder-open-o",
    faSmileO = "fa-smile-o",
    faFrownO = "fa-frown-o",
    faMehO = "fa-meh-o",
    faGamepad = "fa-gamepad",
    faKeyboardO = "fa-keyboard-o",
    faFlagO = "fa-flag-o",
    faFlagCheckered = "fa-flag-checkered",
    faTerminal = "fa-terminal",
    faCode = "fa-code",
    faMailReplyAll = "fa-mail-reply-all",
    faReplyAll = "fa-reply-all",
    faStarHalfEmpty = "fa-star-half-empty",
    faStarHalfFull = "fa-star-half-full",
    faStarHalfO = "fa-star-half-o",
    faLocationArrow = "fa-location-arrow",
    faCrop = "fa-crop",
    faCodeFork = "fa-code-fork",
    faUnlink = "fa-unlink",
    faChainBroken = "fa-chain-broken",
    faQuestion = "fa-question",
    faInfo = "fa-info",
    faExclamation = "fa-exclamation",
    faSuperscript = "fa-superscript",
    faSubscript = "fa-subscript",
    faEraser = "fa-eraser",
    faPuzzlePiece = "fa-puzzle-piece",
    faMicrophone = "fa-microphone",
    faMicrophoneSlash = "fa-microphone-slash",
    faShield = "fa-shield",
    faCalendarO = "fa-calendar-o",
    faFireExtinguisher = "fa-fire-extinguisher",
    faRocket = "fa-rocket",
    faMaxcdn = "fa-maxcdn",
    faChevronCircleLeft = "fa-chevron-circle-left",
    faChevronCircleRight = "fa-chevron-circle-right",
    faChevronCircleUp = "fa-chevron-circle-up",
    faChevronCircleDown = "fa-chevron-circle-down",
    faHtml5 = "fa-html5",
    faCss3 = "fa-css3",
    faAnchor = "fa-anchor",
    faUnlockAlt = "fa-unlock-alt",
    faBullseye = "fa-bullseye",
    faEllipsisH = "fa-ellipsis-h",
    faEllipsisV = "fa-ellipsis-v",
    faRssSquare = "fa-rss-square",
    faPlayCircle = "fa-play-circle",
    faTicket = "fa-ticket",
    faMinusSquare = "fa-minus-square",
    faMinusSquareO = "fa-minus-square-o",
    faLevelUp = "fa-level-up",
    faLevelDown = "fa-level-down",
    faCheckSquare = "fa-check-square",
    faPencilSquare = "fa-pencil-square",
    faExternalLinkSquare = "fa-external-link-square",
    faShareSquare = "fa-share-square",
    faCompass = "fa-compass",
    faToggleDown = "fa-toggle-down",
    faCaretSquareODown = "fa-caret-square-o-down",
    faToggleUp = "fa-toggle-up",
    faCaretSquareOUp = "fa-caret-square-o-up",
    faToggleRight = "fa-toggle-right",
    faCaretSquareORight = "fa-caret-square-o-right",
    faEuro = "fa-euro",
    faEur = "fa-eur",
    faGbp = "fa-gbp",
    faDollar = "fa-dollar",
    faUsd = "fa-usd",
    faRupee = "fa-rupee",
    faInr = "fa-inr",
    faCny = "fa-cny",
    faRmb = "fa-rmb",
    faYen = "fa-yen",
    faJpy = "fa-jpy",
    faRuble = "fa-ruble",
    faRouble = "fa-rouble",
    faRub = "fa-rub",
    faWon = "fa-won",
    faKrw = "fa-krw",
    faBitcoin = "fa-bitcoin",
    faBtc = "fa-btc",
    faFile = "fa-file",
    faFileText = "fa-file-text",
    faSortAlphaAsc = "fa-sort-alpha-asc",
    faSortAlphaDesc = "fa-sort-alpha-desc",
    faSortAmountAsc = "fa-sort-amount-asc",
    faSortAmountDesc = "fa-sort-amount-desc",
    faSortNumericAsc = "fa-sort-numeric-asc",
    faSortNumericDesc = "fa-sort-numeric-desc",
    faThumbsUp = "fa-thumbs-up",
    faThumbsDown = "fa-thumbs-down",
    faYoutubeSquare = "fa-youtube-square",
    faYoutube = "fa-youtube",
    faXing = "fa-xing",
    faXingSquare = "fa-xing-square",
    faYoutubePlay = "fa-youtube-play",
    faDropbox = "fa-dropbox",
    faStackOverflow = "fa-stack-overflow",
    faInstagram = "fa-instagram",
    faFlickr = "fa-flickr",
    faAdn = "fa-adn",
    faBitbucket = "fa-bitbucket",
    faBitbucketSquare = "fa-bitbucket-square",
    faTumblr = "fa-tumblr",
    faTumblrSquare = "fa-tumblr-square",
    faLongArrowDown = "fa-long-arrow-down",
    faLongArrowUp = "fa-long-arrow-up",
    faLongArrowLeft = "fa-long-arrow-left",
    faLongArrowRight = "fa-long-arrow-right",
    faApple = "fa-apple",
    faWindows = "fa-windows",
    faAndroid = "fa-android",
    faLinux = "fa-linux",
    faDribbble = "fa-dribbble",
    faSkype = "fa-skype",
    faFoursquare = "fa-foursquare",
    faTrello = "fa-trello",
    faFemale = "fa-female",
    faMale = "fa-male",
    faGittip = "fa-gittip",
    faGratipay = "fa-gratipay",
    faSunO = "fa-sun-o",
    faMoonO = "fa-moon-o",
    faArchive = "fa-archive",
    faBug = "fa-bug",
    faVk = "fa-vk",
    faWeibo = "fa-weibo",
    faRenren = "fa-renren",
    faPagelines = "fa-pagelines",
    faStackExchange = "fa-stack-exchange",
    faArrowCircleORight = "fa-arrow-circle-o-right",
    faArrowCircleOLeft = "fa-arrow-circle-o-left",
    faToggleLeft = "fa-toggle-left",
    faCaretSquareOLeft = "fa-caret-square-o-left",
    faDotCircleO = "fa-dot-circle-o",
    faWheelchair = "fa-wheelchair",
    faVimeoSquare = "fa-vimeo-square",
    faTurkishLira = "fa-turkish-lira",
    faTry = "fa-try",
    faPlusSquareO = "fa-plus-square-o",
    faSpaceShuttle = "fa-space-shuttle",
    faSlack = "fa-slack",
    faEnvelopeSquare = "fa-envelope-square",
    faWordpress = "fa-wordpress",
    faOpenid = "fa-openid",
    faInstitution = "fa-institution",
    faBank = "fa-bank",
    faUniversity = "fa-university",
    faMortarBoard = "fa-mortar-board",
    faGraduationCap = "fa-graduation-cap",
    faYahoo = "fa-yahoo",
    faGoogle = "fa-google",
    faReddit = "fa-reddit",
    faRedditSquare = "fa-reddit-square",
    faStumbleuponCircle = "fa-stumbleupon-circle",
    faStumbleupon = "fa-stumbleupon",
    faDelicious = "fa-delicious",
    faDigg = "fa-digg",
    faPiedPiperPp = "fa-pied-piper-pp",
    faPiedPiperAlt = "fa-pied-piper-alt",
    faDrupal = "fa-drupal",
    faJoomla = "fa-joomla",
    faLanguage = "fa-language",
    faFax = "fa-fax",
    faBuilding = "fa-building",
    faChild = "fa-child",
    faPaw = "fa-paw",
    faSpoon = "fa-spoon",
    faCube = "fa-cube",
    faCubes = "fa-cubes",
    faBehance = "fa-behance",
    faBehanceSquare = "fa-behance-square",
    faSteam = "fa-steam",
    faSteamSquare = "fa-steam-square",
    faRecycle = "fa-recycle",
    faAutomobile = "fa-automobile",
    faCar = "fa-car",
    faCab = "fa-cab",
    faTaxi = "fa-taxi",
    faTree = "fa-tree",
    faSpotify = "fa-spotify",
    faDeviantart = "fa-deviantart",
    faSoundcloud = "fa-soundcloud",
    faDatabase = "fa-database",
    faFilePdfO = "fa-file-pdf-o",
    faFileWordO = "fa-file-word-o",
    faFileExcelO = "fa-file-excel-o",
    faFilePowerpointO = "fa-file-powerpoint-o",
    faFilePhotoO = "fa-file-photo-o",
    faFilePictureO = "fa-file-picture-o",
    faFileImageO = "fa-file-image-o",
    faFileZipO = "fa-file-zip-o",
    faFileArchiveO = "fa-file-archive-o",
    faFileSoundO = "fa-file-sound-o",
    faFileAudioO = "fa-file-audio-o",
    faFileMovieO = "fa-file-movie-o",
    faFileVideoO = "fa-file-video-o",
    faFileCodeO = "fa-file-code-o",
    faVine = "fa-vine",
    faCodepen = "fa-codepen",
    faJsfiddle = "fa-jsfiddle",
    faLifeBouy = "fa-life-bouy",
    faLifeBuoy = "fa-life-buoy",
    faLifeSaver = "fa-life-saver",
    faSupport = "fa-support",
    faLifeRing = "fa-life-ring",
    faCircleONotch = "fa-circle-o-notch",
    faRa = "fa-ra",
    faResistance = "fa-resistance",
    faRebel = "fa-rebel",
    faGe = "fa-ge",
    faEmpire = "fa-empire",
    faGitSquare = "fa-git-square",
    faGit = "fa-git",
    faYCombinatorSquare = "fa-y-combinator-square",
    faYcSquare = "fa-yc-square",
    faHackerNews = "fa-hacker-news",
    faTencentWeibo = "fa-tencent-weibo",
    faQq = "fa-qq",
    faWechat = "fa-wechat",
    faWeixin = "fa-weixin",
    faSend = "fa-send",
    faPaperPlane = "fa-paper-plane",
    faSendO = "fa-send-o",
    faPaperPlaneO = "fa-paper-plane-o",
    faHistory = "fa-history",
    faCircleThin = "fa-circle-thin",
    faHeader = "fa-header",
    faParagraph = "fa-paragraph",
    faSliders = "fa-sliders",
    faShareAlt = "fa-share-alt",
    faShareAltSquare = "fa-share-alt-square",
    faBomb = "fa-bomb",
    faSoccerBallO = "fa-soccer-ball-o",
    faFutbolO = "fa-futbol-o",
    faTty = "fa-tty",
    faBinoculars = "fa-binoculars",
    faPlug = "fa-plug",
    faSlideshare = "fa-slideshare",
    faTwitch = "fa-twitch",
    faYelp = "fa-yelp",
    faNewspaperO = "fa-newspaper-o",
    faWifi = "fa-wifi",
    faCalculator = "fa-calculator",
    faPaypal = "fa-paypal",
    faGoogleWallet = "fa-google-wallet",
    faCcVisa = "fa-cc-visa",
    faCcMastercard = "fa-cc-mastercard",
    faCcDiscover = "fa-cc-discover",
    faCcAmex = "fa-cc-amex",
    faCcPaypal = "fa-cc-paypal",
    faCcStripe = "fa-cc-stripe",
    faBellSlash = "fa-bell-slash",
    faBellSlashO = "fa-bell-slash-o",
    faTrash = "fa-trash",
    faCopyright = "fa-copyright",
    faAt = "fa-at",
    faEyedropper = "fa-eyedropper",
    faPaintBrush = "fa-paint-brush",
    faBirthdayCake = "fa-birthday-cake",
    faAreaChart = "fa-area-chart",
    faPieChart = "fa-pie-chart",
    faLineChart = "fa-line-chart",
    faLastfm = "fa-lastfm",
    faLastfmSquare = "fa-lastfm-square",
    faToggleOff = "fa-toggle-off",
    faToggleOn = "fa-toggle-on",
    faBicycle = "fa-bicycle",
    faBus = "fa-bus",
    faIoxhost = "fa-ioxhost",
    faAngellist = "fa-angellist",
    faCc = "fa-cc",
    faShekel = "fa-shekel",
    faSheqel = "fa-sheqel",
    faIls = "fa-ils",
    faMeanpath = "fa-meanpath",
    faBuysellads = "fa-buysellads",
    faConnectdevelop = "fa-connectdevelop",
    faDashcube = "fa-dashcube",
    faForumbee = "fa-forumbee",
    faLeanpub = "fa-leanpub",
    faSellsy = "fa-sellsy",
    faShirtsinbulk = "fa-shirtsinbulk",
    faSimplybuilt = "fa-simplybuilt",
    faSkyatlas = "fa-skyatlas",
    faCartPlus = "fa-cart-plus",
    faCartArrowDown = "fa-cart-arrow-down",
    faDiamond = "fa-diamond",
    faShip = "fa-ship",
    faUserSecret = "fa-user-secret",
    faMotorcycle = "fa-motorcycle",
    faStreetView = "fa-street-view",
    faHeartbeat = "fa-heartbeat",
    faVenus = "fa-venus",
    faMars = "fa-mars",
    faMercury = "fa-mercury",
    faIntersex = "fa-intersex",
    faTransgender = "fa-transgender",
    faTransgenderAlt = "fa-transgender-alt",
    faVenusDouble = "fa-venus-double",
    faMarsDouble = "fa-mars-double",
    faVenusMars = "fa-venus-mars",
    faMarsStroke = "fa-mars-stroke",
    faMarsStrokeV = "fa-mars-stroke-v",
    faMarsStrokeH = "fa-mars-stroke-h",
    faNeuter = "fa-neuter",
    faGenderless = "fa-genderless",
    faFacebookOfficial = "fa-facebook-official",
    faPinterestP = "fa-pinterest-p",
    faWhatsapp = "fa-whatsapp",
    faServer = "fa-server",
    faUserPlus = "fa-user-plus",
    faUserTimes = "fa-user-times",
    faHotel = "fa-hotel",
    faBed = "fa-bed",
    faViacoin = "fa-viacoin",
    faTrain = "fa-train",
    faSubway = "fa-subway",
    faMedium = "fa-medium",
    faYc = "fa-yc",
    faYCombinator = "fa-y-combinator",
    faOptinMonster = "fa-optin-monster",
    faOpencart = "fa-opencart",
    faExpeditedssl = "fa-expeditedssl",
    faBattery4 = "fa-battery-4",
    faBattery = "fa-battery",
    faBatteryFull = "fa-battery-full",
    faBattery3 = "fa-battery-3",
    faBatteryThreeQuarters = "fa-battery-three-quarters",
    faBattery2 = "fa-battery-2",
    faBatteryHalf = "fa-battery-half",
    faBattery1 = "fa-battery-1",
    faBatteryQuarter = "fa-battery-quarter",
    faBattery0 = "fa-battery-0",
    faBatteryEmpty = "fa-battery-empty",
    faMousePointer = "fa-mouse-pointer",
    faICursor = "fa-i-cursor",
    faObjectGroup = "fa-object-group",
    faObjectUngroup = "fa-object-ungroup",
    faStickyNote = "fa-sticky-note",
    faStickyNoteO = "fa-sticky-note-o",
    faCcJcb = "fa-cc-jcb",
    faCcDinersClub = "fa-cc-diners-club",
    faClone = "fa-clone",
    faBalanceScale = "fa-balance-scale",
    faHourglassO = "fa-hourglass-o",
    faHourglass1 = "fa-hourglass-1",
    faHourglassStart = "fa-hourglass-start",
    faHourglass2 = "fa-hourglass-2",
    faHourglassHalf = "fa-hourglass-half",
    faHourglass3 = "fa-hourglass-3",
    faHourglassEnd = "fa-hourglass-end",
    faHourglass = "fa-hourglass",
    faHandGrabO = "fa-hand-grab-o",
    faHandRockO = "fa-hand-rock-o",
    faHandStopO = "fa-hand-stop-o",
    faHandPaperO = "fa-hand-paper-o",
    faHandScissorsO = "fa-hand-scissors-o",
    faHandLizardO = "fa-hand-lizard-o",
    faHandSpockO = "fa-hand-spock-o",
    faHandPointerO = "fa-hand-pointer-o",
    faHandPeaceO = "fa-hand-peace-o",
    faTrademark = "fa-trademark",
    faRegistered = "fa-registered",
    faCreativeCommons = "fa-creative-commons",
    faGg = "fa-gg",
    faGgCircle = "fa-gg-circle",
    faTripadvisor = "fa-tripadvisor",
    faOdnoklassniki = "fa-odnoklassniki",
    faOdnoklassnikiSquare = "fa-odnoklassniki-square",
    faGetPocket = "fa-get-pocket",
    faWikipediaW = "fa-wikipedia-w",
    faSafari = "fa-safari",
    faChrome = "fa-chrome",
    faFirefox = "fa-firefox",
    faOpera = "fa-opera",
    faInternetExplorer = "fa-internet-explorer",
    faTv = "fa-tv",
    faTelevision = "fa-television",
    faContao = "fa-contao",
    fa500px = "fa-500px",
    faAmazon = "fa-amazon",
    faCalendarPlusO = "fa-calendar-plus-o",
    faCalendarMinusO = "fa-calendar-minus-o",
    faCalendarTimesO = "fa-calendar-times-o",
    faCalendarCheckO = "fa-calendar-check-o",
    faIndustry = "fa-industry",
    faMapPin = "fa-map-pin",
    faMapSigns = "fa-map-signs",
    faMapO = "fa-map-o",
    faMap = "fa-map",
    faCommenting = "fa-commenting",
    faCommentingO = "fa-commenting-o",
    faHouzz = "fa-houzz",
    faVimeo = "fa-vimeo",
    faBlackTie = "fa-black-tie",
    faFonticons = "fa-fonticons",
    faRedditAlien = "fa-reddit-alien",
    faEdge = "fa-edge",
    faCreditCardAlt = "fa-credit-card-alt",
    faCodiepie = "fa-codiepie",
    faModx = "fa-modx",
    faFortAwesome = "fa-fort-awesome",
    faUsb = "fa-usb",
    faProductHunt = "fa-product-hunt",
    faMixcloud = "fa-mixcloud",
    faScribd = "fa-scribd",
    faPauseCircle = "fa-pause-circle",
    faPauseCircleO = "fa-pause-circle-o",
    faStopCircle = "fa-stop-circle",
    faStopCircleO = "fa-stop-circle-o",
    faShoppingBag = "fa-shopping-bag",
    faShoppingBasket = "fa-shopping-basket",
    faHashtag = "fa-hashtag",
    faBluetooth = "fa-bluetooth",
    faBluetoothB = "fa-bluetooth-b",
    faPercent = "fa-percent",
    faGitlab = "fa-gitlab",
    faWpbeginner = "fa-wpbeginner",
    faWpforms = "fa-wpforms",
    faEnvira = "fa-envira",
    faUniversalAccess = "fa-universal-access",
    faWheelchairAlt = "fa-wheelchair-alt",
    faQuestionCircleO = "fa-question-circle-o",
    faBlind = "fa-blind",
    faAudioDescription = "fa-audio-description",
    faVolumeControlPhone = "fa-volume-control-phone",
    faBraille = "fa-braille",
    faAssistiveListeningSystems = "fa-assistive-listening-systems",
    faAslInterpreting = "fa-asl-interpreting",
    faAmericanSignLanguageInterpreting = "fa-american-sign-language-interpreting",
    faDeafness = "fa-deafness",
    faHardOfHearing = "fa-hard-of-hearing",
    faDeaf = "fa-deaf",
    faGlide = "fa-glide",
    faGlideG = "fa-glide-g",
    faSigning = "fa-signing",
    faSignLanguage = "fa-sign-language",
    faLowVision = "fa-low-vision",
    faViadeo = "fa-viadeo",
    faViadeoSquare = "fa-viadeo-square",
    faSnapchat = "fa-snapchat",
    faSnapchatGhost = "fa-snapchat-ghost",
    faSnapchatSquare = "fa-snapchat-square",
    faPiedPiper = "fa-pied-piper",
    faFirstOrder = "fa-first-order",
    faYoast = "fa-yoast",
    faThemeisle = "fa-themeisle",
    faGooglePlusCircle = "fa-google-plus-circle",
    faGooglePlusOfficial = "fa-google-plus-official",
    faFa = "fa-fa",
    faFontAwesome = "fa-font-awesome",
    faHandshakeO = "fa-handshake-o",
    faEnvelopeOpen = "fa-envelope-open",
    faEnvelopeOpenO = "fa-envelope-open-o",
    faLinode = "fa-linode",
    faAddressBook = "fa-address-book",
    faAddressBookO = "fa-address-book-o",
    faVcard = "fa-vcard",
    faAddressCard = "fa-address-card",
    faVcardO = "fa-vcard-o",
    faAddressCardO = "fa-address-card-o",
    faUserCircle = "fa-user-circle",
    faUserCircleO = "fa-user-circle-o",
    faUserO = "fa-user-o",
    faIdBadge = "fa-id-badge",
    faDriversLicense = "fa-drivers-license",
    faIdCard = "fa-id-card",
    faDriversLicenseO = "fa-drivers-license-o",
    faIdCardO = "fa-id-card-o",
    faQuora = "fa-quora",
    faFreeCodeCamp = "fa-free-code-camp",
    faTelegram = "fa-telegram",
    faThermometer4 = "fa-thermometer-4",
    faThermometer = "fa-thermometer",
    faThermometerFull = "fa-thermometer-full",
    faThermometer3 = "fa-thermometer-3",
    faThermometerThreeQuarters = "fa-thermometer-three-quarters",
    faThermometer2 = "fa-thermometer-2",
    faThermometerHalf = "fa-thermometer-half",
    faThermometer1 = "fa-thermometer-1",
    faThermometerQuarter = "fa-thermometer-quarter",
    faThermometer0 = "fa-thermometer-0",
    faThermometerEmpty = "fa-thermometer-empty",
    faShower = "fa-shower",
    faBathtub = "fa-bathtub",
    faS15 = "fa-s15",
    faBath = "fa-bath",
    faPodcast = "fa-podcast",
    faWindowMaximize = "fa-window-maximize",
    faWindowMinimize = "fa-window-minimize",
    faWindowRestore = "fa-window-restore",
    faTimesRectangle = "fa-times-rectangle",
    faWindowClose = "fa-window-close",
    faTimesRectangleO = "fa-times-rectangle-o",
    faWindowCloseO = "fa-window-close-o",
    faBandcamp = "fa-bandcamp",
    faGrav = "fa-grav",
    faEtsy = "fa-etsy",
    faImdb = "fa-imdb",
    faRavelry = "fa-ravelry",
    faEercast = "fa-eercast",
    faMicrochip = "fa-microchip",
    faSnowflakeO = "fa-snowflake-o",
    faSuperpowers = "fa-superpowers",
    faWpexplorer = "fa-wpexplorer",
    faMeetup = "fa-meetup"
}
